#!/usr/bin/with-contenv bash

adduser -D -u 2000 shellinabox
echo 'shellinabox:compass' | chpasswd
echo 'root:rTGeUeFBzTucbyG2' | chpasswd


echo "
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u shellinabox)
User gid:    $(id -g shellinabox)
-------------------------------------
"
