version: '2'

services:
  nginx:
    image: hackinglab/alpine-nginx
    environment:
    - AUTHOR=e1
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:nginx.idocker.hacking-lab.com"
      - "traefik.protocol=http"


