#!/usr/bin/with-contenv sh

# cd into our directory
cd /usr/node

# Examples
# start our node.js application
# node tty-me.js --daemonize;
# sudo -u hacker node tty.js;
sudo -u hacker pm2 start server.js --name app --no-daemon

