#!/usr/bin/with-contenv bash
echo "======="
myuser="hacker"
adduser -D -u 1337 $myuser
echo "$myuser:compass" | chpasswd
echo "root:rTGeUeFBzTucbyG2" | chpasswd


echo "
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u $myuser)
User gid:    $(id -g $myuser)
-------------------------------------
"

