version: '2'

services:
  openssh-server: 
    image: hackinglab/alpine-openssh-server
    environment:
    - AUTHOR=e1
    - HL_USER_USERNAME=hacker
    - HL_USER_PASSWORD=compass
    ports:
      - "22:22"


