#!/usr/bin/with-contenv bash

echo ""
echo "====== testing for flag in environment variable ======="
if [ -z "$GOLDNUGGET" ]
then
      echo "no flag found in environment variable $GOLDNUGGET"
else
      echo "flag found in environment variable GOLDNUGGET=$GOLDNUGGET"
      echo "what do you want to do with the flag in the environment variable?"
      echo "please define what you want to do with the flag in /flag-deploy-scripts/deploy-env-flag.sh"

      if test -f ""/flag-deploy-scripts/deploy-env-flag.sh; then
	echo "executing /flag-deploy-scripts/deploy-env-flag.sh"
        bash /flag-deploy-scripts/deploy-env-flag.sh
      else
	echo "script /flag-deploy-scripts/deploy-env-flag.sh not available - do nothing"
        echo "mount this script from outside of your docker via volumes command"
      fi
fi

echo ""
echo "====== testing for flag in /goldnugget folder ======"

if [ "$(ls -A /goldnugget)" ]; then
      echo "flag file found in /goldnugget"
      ls -lA /goldnugget
      echo "what do you want to do with the flag file?"
      echo "please define what you want to do with the flag in /flag-deploy-scripts/deploy-file-flag.sh"

      if test -f ""/flag-deploy-scripts/deploy-file-flag.sh; then
        echo "executing /flag-deploy-scripts/deploy-file-flag.sh"
        bash /flag-deploy-scripts/deploy-file-flag.sh
      else
        echo "script /flag-deploy-scripts/deploy-file-flag.sh not available - do nothing"
        echo "mount this script from outside of your docker via volumes command"
      fi
else
      echo "No flag file found in /goldnugget"
fi

echo ""
echo "============================================="
