version: '2.0'

services:

    nginx:
        image: hackinglab/alpine-nginx-php
        labels:
            - "traefik.attacker.port=80"
            - "traefik.attacker.frontend.rule=Host:nginx-php.idocker.hacking-lab.com"
            - "traefik.attacker.protocol=http"
        environment:
            - TZ=Europe/Zurich
