#!/usr/bin/with-contenv bash

myuser="abc"
adduser -D -u 2000 $myuser
echo "$myuser:compass" | chpasswd
echo 'root:rTGeUeFBzTucbyG2' | chpasswd


echo "
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u $myuser)
User gid:    $(id -g $myuser)
-------------------------------------
"
chown $myuser:$myuser /app
chown $myuser:$myuser /config
chown $myuser:$myuser /defaults
