#!/usr/bin/with-contenv bash

adduser -D -u 2000 abc
echo 'abc:compass' | chpasswd
echo 'root:rTGeUeFBzTucbyG2' | chpasswd


echo "
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults
